apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
  - name: logs
    image: afakharany/watcher
    ports:
    - name: watcher-port
      containerPort: 8000
 
